### ISSUE TITLE
Begin documenting a setup guide for contributors

### ISSUE THREAD

**Issue by felpsey** [felpsey/open-bot-interface#4]
Document how the environment should be setup locally and Discord configuration.

**Comment by gpc91** [comment]
I started working on README yesterday but yours was made a lot quicker and more verbose than mine. Some changes that I'd maybe bring forward would be to have both a quick-guide as well as a more in-depth one. 

The quick-guide could benefit with checkboxes to make following along easier. As for the in-depth guide, would you like me to continue working on that and add a pull request with images and all?

Here is what I have on my version of the quick guide so far.

---

## Installation and setup for contributors
### Requirements
 - [Node.js](https://nodejs.org/en/)
 - Discord server with the **Manage server** permission.
 
### Quick guide
#### Bot set up
 - [ ] Clone this repository.
 - [ ] Log in to the [Discord Developer Portal -> Applications](https://discord.com/developers/applications) page and create a new application.
 - [ ] Make a note of your **Application ID** on the *General Information* tab.
 - [ ] Go to the *Bot* tab and create a bot and then copy the **Token**
 - [ ] Go the the *OAuth2* page and **in the scopes box** select **bot** and **applications.commands**.
 - [ ] Under **bot permissions** select *administrator*. Copy the URL this page has generated safe to use later.
 - [ ] In a server that you that you have **Manage server** permissions go to the **widgets**  tab and copy the **Server ID**.
 - [ ] Navigate to where you have cloned the github repo to and copy the *.env-exmaple* to *.env*
 - [ ] In this new *.env* fill in and save the relevant values that you have copied (*Application ID*, *Bot Token*, and *Server ID*).
 - [ ] Now navigate to the URL that you saved earlier and if prompted log in to your discord account. Choose the server you want to invite the bot to and click "Authorize".

Having followed these instructions you should now have the bot in your server and the relevant information in your *.env* file.
 #### Server set up
  - [ ] If you do not have [Node.js](https://nodejs.org/en/) installed, install it now.
  - [ ] Open up your computer terminal and navigate to your project folder.
  - [ ] Install all dependencies by using the command `npm install`
  - [ ] Now, you should be able to run the bot using `node index.js`

**Comment by felpsey** [comment]
Will revisit documentation as project grows along with @gpc91 's suggestions.
